version: "3.9"

services:
  db:
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
    healthcheck:
      disable: true
  web:
    volumes:
      - .:/{{cookiecutter.project_slug}}
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    command: bin/dev
    tty: true

networks:
  # For local dev, don't expect an external Traefik network
  traefik-public:
    external: false

secrets:
  {{cookiecutter.postgres_password_secret_name}}:
    file: ./secrets/{{cookiecutter.postgres_password_secret_name}}.txt
    external: false
